example.property: ""
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/user_storage"
spring.datasource.username: "postgres"
spring.datasource.password: {cipher} Jgfymrb
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
signing.key: "345345fsdfsf5345"
management.endpoints.web.exposure.include: "*"
